name: image_cropper_for_web
description: A Flutter plugin for Web supports cropping images
repository: https://github.com/hnvn/flutter_image_cropper
version: 5.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  image_cropper_platform_interface: ^6.1.0

  web: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: image_cropper
    platforms:
      web:
        pluginClass: ImageCropperPlugin
        fileName: image_cropper_for_web.dart
