name: image_cropper
description: A Flutter plugin for Android and iOS supports cropping images
version: 1.2.3
author: Hung Duy Ha <hunghd.yb@gmail.com>
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=1.20.1 <3.0.0'
  flutter: ^1.12.13

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: vn.hunghd.flutter.plugins.imagecropper
    iosPrefix: FLT
    pluginClass: ImageCropperPlugin