name: image_cropper_platform_interface
description: A common platform interface for the image_cropper plugin.
repository: https://github.com/hnvn/flutter_image_cropper
version: 3.0.4

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
