name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 6.0.0
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin
      web:
        default_package: image_cropper_for_web

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface:
    path: ../image_cropper_platform_interface
  image_cropper_for_web: 
    path: ../image_cropper_for_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
