name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 2.0.0-beta.3
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin
      web:
        default_package: image_cropper_for_web

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface: ^2.0.0-beta.1
  image_cropper_for_web: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0