name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 7.0.6
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin
      web:
        default_package: image_cropper_for_web

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface: ^6.0.3
  image_cropper_for_web: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
